// Safety net for testing godotBuilder.jsfl/inspector.jsfl WITHOUT Adobe
// Animate: runs the full pipeline (buildGodotScenes) in a Node.js sandbox,
// starting from a debug_data.json already extracted from a real .fla (see
// readme.md, "debug_data.json" is generated by main.jsfl on every export),
// and writes every "generated" file to disk so it can be diffed between two
// versions of the code.
//
// Usage:
//   node tools/pipeline_snapshot.js <debug_data.json> <output_snapshot_dir>
//
// Workflow for validating a change in modules/godotBuilder.jsfl or
// modules/inspector.jsfl WITHOUT touching Adobe Animate:
//   1. BEFORE modifying the code: generate a reference snapshot.
//        node tools/pipeline_snapshot.js debug_data.json /tmp/before
//   2. Make the change.
//   3. AFTER: regenerate into another folder.
//        node tools/pipeline_snapshot.js debug_data.json /tmp/after
//   4. Compare:
//        diff -rq /tmp/before /tmp/after
//      Every difference must be EXPLAINABLE by the intended change. An
//      unexpected difference = a regression caught before even opening
//      Godot.
//
// If debug_data.json was generated by an older version of jsflStringify
// (main.jsfl), JSON.parse may fail on unescaped control characters (bug
// fixed since) -- run it through tools/repair_debug_json.js first in that
// case.
"use strict";

const fs = require('fs');
const path = require('path');
const vm = require('vm');

const REPO_ROOT = path.join(__dirname, '..');

function loadData(jsonPath) {
    const text = fs.readFileSync(jsonPath, 'utf8');
    return JSON.parse(text);
}

function runPipeline(data, exportDir, builderPathOverride) {
    const written = {}; // relPath -> content

    function toRel(p) {
        if (p.indexOf(exportDir) === 0) return p.substring(exportDir.length);
        return p;
    }

    const FLfile = {
        // No project.godot simulated: RES_PREFIX stays "res://" (instead
        // of the res://<subfolder>/ a real export would compute if the
        // chosen folder is a subfolder of the Godot project). Only affects
        // ext_resource paths, not node structure -- no impact when
        // comparing two versions of the CODE against each other.
        exists: function() { return false; },
        // No external PNGs simulated: shapes using customTexPath are not
        // exercised by this harness.
        listFolder: function() { return []; },
        createFolder: function() { /* no-op, implicitly captured via write */ },
        write: function(p, content, mode) {
            const rel = toRel(p);
            if (mode === 'append' && written[rel] !== undefined) {
                written[rel] += content;
            } else {
                written[rel] = content;
            }
        },
    };
    const flObj = {
        trace: function() { /* silent; add console.log here for debugging */ },
        runScript: function() {
            throw new Error('fl.runScript must not be called from within godotBuilder.jsfl/inspector.jsfl themselves');
        },
    };

    const sandbox = { fl: flObj, FLfile: FLfile };
    vm.createContext(sandbox);

    // Loading order IDENTICAL to main.jsfl: inspector.jsfl then
    // godotBuilder.jsfl, in the same global scope (exactly what
    // fl.runScript does in real JSFL -- no module isolation).
    const inspectorSrc = fs.readFileSync(path.join(REPO_ROOT, 'modules', 'inspector.jsfl'), 'utf8');
    const builderSrc = fs.readFileSync(builderPathOverride || path.join(REPO_ROOT, 'modules', 'godotBuilder.jsfl'), 'utf8');
    vm.runInContext(inspectorSrc, sandbox, { filename: 'inspector.jsfl' });
    vm.runInContext(builderSrc, sandbox, { filename: 'godotBuilder.jsfl' });

    // nextId() uses Math.random() in production (unique resource IDs are
    // all that's needed, no requirement for stability) -- but comparing
    // two runs byte-for-byte requires determinism. A simple counter
    // reproduces the exact same ID stream on every run, as long as the
    // code calls nextId() in the same order for the same input data.
    let idCounter = 1;
    sandbox.nextId = function() { return idCounter++; };

    sandbox.__data = data;
    sandbox.__exportDir = exportDir;
    vm.runInContext('buildGodotScenes(null, __data, __exportDir);', sandbox, { filename: 'harness-call' });

    return written;
}

function main() {
    const jsonPath = process.argv[2];
    const outDir = process.argv[3];
    const builderPathOverride = process.env.BUILDER_PATH; // to compare against a historical version (git show <rev>:modules/godotBuilder.jsfl > /tmp/old.jsfl)
    if (!jsonPath || !outDir) {
        console.error('Usage: node tools/pipeline_snapshot.js <debug_data.json> <output_dir>');
        process.exit(1);
    }

    const data = loadData(jsonPath);
    const exportDir = 'C:/fake_export/';
    const written = runPipeline(data, exportDir, builderPathOverride);

    const fileNames = Object.keys(written).sort();
    console.log('Files generated by the pipeline: ' + fileNames.length);

    if (fs.existsSync(outDir)) fs.rmSync(outDir, { recursive: true, force: true });
    fs.mkdirSync(outDir, { recursive: true });
    for (const rel of fileNames) {
        const dest = path.join(outDir, rel);
        fs.mkdirSync(path.dirname(dest), { recursive: true });
        fs.writeFileSync(dest, written[rel], 'utf8');
    }
    console.log('Snapshot written to: ' + outDir);

    let totalBytes = 0;
    for (const rel of fileNames) totalBytes += written[rel].length;
    console.log('Total: ' + totalBytes + ' bytes across ' + fileNames.length + ' files.');
}

main();
